- title: Zero to App Store
  best_if: you need a brand new Turbo Native app and want me to do everything.
  you_get: a developer (me) to build your Android and iOS apps and launch them.
  cta: Email Sebastian to get started
  description: |
    I write all of the native Kotlin/Swift code and Rails integration needed. We can
    integrate with native Apple SDKs, too. I work with your designers and
    developers to teach and apply the best practices I've accumulated working
    with the framework for 7+ years.

- title: Private custom workshop
  best_if: you want to level up your team to write Turbo Native apps on their own.
  you_get: a custom workshop tailored to your team's unique needs and skill level.
  cta: Email Sebastian to get started
  description: |
    Workshops can range from virtual, half-day sessions to in-person, multi-day
    events.  They can cover Kotlin/Swift syntax, dive right into the Turbo
    Native integration, or skip ahead to best practices in building scalable
    hybrid apps with small teams.

- title: Monthly advisory retainer
  best_if: you want to write the code yourself but need an expert to guide you.
  you_get: unlimited access to me via phone, email, and/or Zoom.
  cta: Email Sebastian to get started
  description: |
    Use our time to get advice on best practices, receive technical overviews of
    topics, or even to dive into your Turbo Native code. I return all messages
    no later than the next business day. Meetings must be scheduled in advance.

- title: 1:1 advisory meeting
  price: $299 for a 45 minute call
  best_if: you have a few specific questions on Turbo Native.
  you_get: a live video call to consult with an expert.
  href: https://cal.com/sebastianbachmann
  cta: Schedule a meeting
  description: |
    A private 45-minute video chat with me. Use our time to ask questions, learn
    best practices, or request feedback on your Turbo Native code.
